/* This is a generated file */
#ifndef __jwt_private_h__
#define __jwt_private_h__

#include <stdarg.h>

/*
 * GSS-JWT mechanism private function prototypes
 * Auto-generated by make-proto.pl
 */

#endif /* __jwt_private_h__ */
